#!/usr/bin/env python3
"""
SPARXSTAR EVENT HORIZON v2.0
Copyright (c) 2026 Starisian Technologies. All Rights Reserved.
Proprietary / Closed Source.

SPARXSTAR Event Horizon - Cloudflare IP Range Updater
Fetches the official Cloudflare IP ranges and regenerates
conf.d/spx-cloudflare-trust.conf so the RealIP module always
trusts only verified Cloudflare edge nodes.

Usage:
    python scripts/update_cloudflare.py [--output conf.d/spx-cloudflare-trust.conf]

Run this monthly (or via a cron/CI job) to keep the trust list current.
After running, always validate and reload Nginx:
    sudo nginx -t && sudo systemctl reload nginx
"""

import argparse
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Official Cloudflare IP range endpoints (plain text, one CIDR per line).
CF_V4_URL = "https://www.cloudflare.com/ips-v4"
CF_V6_URL = "https://www.cloudflare.com/ips-v6"

# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "conf.d" / "spx-cloudflare-trust.conf"


def fetch_ip_ranges(url: str) -> list[str]:
    """Fetch a plain-text list of CIDR ranges from *url*."""
    if not url.startswith("https://"):
        print(f"ERROR: Only HTTPS URLs are accepted: {url}", file=sys.stderr)
        sys.exit(1)

    req = urllib.request.Request(
        url,
        headers={"User-Agent": "Mozilla/5.0 (compatible; SPARXSTAR/2.0; +https://github.com/Starisian-Technologies/sparxstar-event-horizon)"},
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as response:
            lines = response.read().decode("utf-8", errors="replace").splitlines()
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as exc:
        print(f"ERROR: Could not fetch {url}: {exc}", file=sys.stderr)
        sys.exit(1)

    return [line.strip() for line in lines if line.strip() and not line.startswith("#")]


def build_config(v4_ranges: list[str], v6_ranges: list[str]) -> str:
    """Generate the Nginx RealIP trust config block."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    all_ranges = v4_ranges + v6_ranges

    lines = [
        "# ======================================================================",
        "# SPARXSTAR EVENT HORIZON — Cloudflare Trust Definitions",
        f"# Auto-generated by scripts/update_cloudflare.py on {timestamp}",
        "# DO NOT edit manually — run the script to refresh.",
        "# ======================================================================",
        "",
        "# 1. TRUST THESE IPs (Cloudflare Edge Proxies)",
        "# ----------------------------------------------------------------------",
        "# Only TCP connections from these ranges are allowed to set the",
        "# CF-Connecting-IP header. All other CF-Connecting-IP values are ignored.",
    ]

    for cidr in all_ranges:
        lines.append(f"set_real_ip_from {cidr};")

    lines += [
        "",
        "# 2. EXTRACT THE REAL CLIENT IP FROM THE TRUSTED HEADER",
        "# ----------------------------------------------------------------------",
        "real_ip_header CF-Connecting-IP;",
        "real_ip_recursive on;",
        "",
        "# Note: If not using Cloudflare, remove this entire file and rely on",
        "# $realip_remote_addr from your load balancer, or $remote_addr directly.",
    ]

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate the Cloudflare RealIP trust config."
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Destination path (default: %(default)s)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated config without writing any file.",
    )
    args = parser.parse_args()

    print("Fetching Cloudflare IPv4 ranges…", flush=True)
    v4 = fetch_ip_ranges(CF_V4_URL)
    print(f"  → {len(v4)} IPv4 ranges", flush=True)

    print("Fetching Cloudflare IPv6 ranges…", flush=True)
    v6 = fetch_ip_ranges(CF_V6_URL)
    print(f"  → {len(v6)} IPv6 ranges", flush=True)

    # Safety check: Ensure we didn't get empty lists
    if not v4 or not v6:
        print("ERROR: Cloudflare IP list empty — aborting.", file=sys.stderr)
        sys.exit(1)

    config = build_config(v4, v6)

    if args.dry_run:
        print("\n--- Generated config (dry-run) ---")
        print(config)
        return

    output_path = Path(args.output).resolve()
    # Atomic write: write to .tmp then rename
    tmp_path = output_path.with_suffix(".tmp")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    try:
        tmp_path.write_text(config, encoding="utf-8")
        tmp_path.replace(output_path)
        print(f"  → Written: {output_path}", flush=True)
    except OSError as exc:
        print(f"ERROR: Could not write to file: {exc}", file=sys.stderr)
        if tmp_path.exists():
            tmp_path.unlink()
        sys.exit(1)
        
    print("Done. Run  nginx -t  to verify syntax before reloading.", flush=True)


if __name__ == "__main__":
    main()
